implemented monochrome ui, binary game mechanic change and formatted …
tedspare/hexle pull request #1
Opened 2022-10-22 15:34 UTC by DexterStorey

A very opinionated ui branch that could use some work / review before merging

2022-10-22 16:00 UTC, DexterStorey commented
I feel like we need to decide on boldness, roundness and font sizing as part of a design system... I made some arbitrary choices here

2022-10-22 16:01 UTC, DexterStorey commented
should the keys be square? also just realizing the padding's inconsistent between the grid and the keyboard

2022-10-22 16:02 UTC, DexterStorey commented
Also wondering if the indicators on top / bottom would look cleaner as small arrows that hug a bit closer to the char

2022-10-22 16:47 UTC, tedspare commented
ITYJ re design system 😅 

---

> Also wondering if the indicators on top / bottom would look cleaner as small arrows that hug a bit closer to the char

Core issue here: does an up/high indicator mean "guess higher" or "you're too high"?
- One approach is to replace "high vs low" with "close vs far". This would make binary search 2x harder too.
- Another is to add a legend: `^ = guess higher`

2022-10-22 16:49 UTC, tedspare commented on src/pages/index.tsx
> +  return distance < 0 ? HINT.UP : distance == 0 ? HINT.HIT : HINT.DOWN;
I like this

2022-10-22 16:52 UTC, tedspare commented on src/pages/index.tsx
> +            {hexes.map((_hex: string, i: number) => (
`_hex` -> `char` maybe? For clarity

2022-10-22 16:54 UTC, tedspare commented on src/pages/index.tsx
> +              style={{ color: `#${hex}`, backgroundColor: contrastColor }}
Could parametrize `const color = '#${hex}'` above

2022-10-22 16:55 UTC, tedspare commented on src/styles/globals.css
> +    @apply center h-16 w-12 cursor-pointer font-bold transition-transform hover:scale-110;
`transition-transform` -> `transition-all` for the hover color

2022-10-22 16:56 UTC, tedspare requested changes
Generally LGTM; nitpicks only

2022-10-22 17:50 UTC, DexterStorey commented
> LGTM
R u even a FAANG PM

2022-11-03 15:15 UTC, DexterStorey commented
> Generally LGTM; nitpicks only

Check it out I think this is ready to go

2022-11-03 16:43 UTC, DexterStorey commented
Looks good on small mobile

![image](https://user-images.githubusercontent.com/36115192/199781540-52df3c32-214d-4e44-8462-e96f8d1efe7f.png)

2022-11-04 00:00 UTC, DexterStorey commented
@tedspare Can you review?

Need help testing the social media preview and Fav coverage on your browsers

Otherwise I think this is good to go- I'll make new prs for styling fine tuning later but I want to merge so I can branch off main for some of the new features

2022-11-04 00:01 UTC, DexterStorey commented
TLDR there's some big ui changes with spacing and sizing - it's very mobile first, but desktop could use a little love when we get a chance

2022-11-04 19:41 UTC, tedspare commented on src/pages/api/favicon.tsx
> +            flexWrap: "nowrap",
you really hate Tailwind eh

2022-11-04 19:41 UTC, tedspare commented on src/pages/api/favicon.tsx
> +            flexWrap: "nowrap",
nvm this is the favicon hoooly

2022-11-04 19:42 UTC, tedspare commented on src/pages/api/og.tsx
> +  runtime: "experimental-edge",
❤️

2022-11-04 19:44 UTC, tedspare commented
@DexterStorey LGTM 🚢 🚢 🚢

2022-11-04 19:49 UTC, tedspare commented
Favicon in Arc browser looks good
<img width="177" alt="image" src="https://user-images.githubusercontent.com/36117635/200062266-76d658bd-1efe-456a-9ad3-d3859f8ec93c.png">

Social preview in Slack is a different color but looks good
<img width="409" alt="image" src="https://user-images.githubusercontent.com/36117635/200062313-4680dead-a067-4053-b1f0-343fb41ad10e.png">

Lost (I suck at this game so far lol) but didn't get the alert
![image](https://user-images.githubusercontent.com/36117635/200062504-ca6b9645-bb90-4c2f-a974-f4c34be8f719.png)

Also keyboard doesn't show `active:` animations anymore - intentional?

2022-11-04 19:56 UTC, DexterStorey commented
> Also keyboard doesn't show `active:` animations anymore - intentional?

removed with the monochrome ui - unless you can think of a way to show active that doesn't involve transparency / color? - it seems too quirky to make it bounce or invert..

Maybe we can make this a new issue about broader monochrome constraints and then think about ways to handle multiple states and notifications with monochrome ui?

2022-11-04 19:57 UTC, DexterStorey commented
We also need to design monochrome ui for alerts / win / loss conditions but I'll make this an issue and self assign

2022-11-04 20:07 UTC, DexterStorey commented
F it I'm merging

This merge closes issues #4 and #5 

#8 and #9 are created as a result of the breaking changes in this branch

2022-11-04 20:08 UTC, merged